version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 038462784735.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building frontend Docker image...
      - docker build -t energy-frontend:latest ./community-energy-connect-Final/frontend
      - docker tag energy-frontend:latest 038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-frontend:latest
      - echo Building backend Docker image...
      - docker build -t energy-backend:latest ./community-energy-connect-Final/backend
      - docker tag energy-backend:latest 038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-backend:latest

  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push 038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-frontend:latest
      - docker push 038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-backend:latest
      - echo Updating Kubernetes deployment on EKS...
      - aws eks update-kubeconfig --region us-east-1 --name MyRenamedEKSCluster
      

artifacts:
  files:
    - '**/*'
