version: 0.2
 
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 038462784735.dkr.ecr.us-east-2.amazonaws.com
 
  build:
    commands:
      - echo Build started on `date`
      - echo Building frontend Docker image...
      - docker build -t energy-frontend:latest ./community-energy-connect-Final/frontend
      - docker tag energy-frontend:latest 038462784735.dkr.ecr.us-east-2.amazonaws.com/energy-frontend-v2
 
      - echo Building backend Docker image...
      - docker build -t energy-backend:latest ./community-energy-connect-Final/backend
      - docker tag energy-backend:latest 038462784735.dkr.ecr.us-east-2.amazonaws.com/energy-backend-v2
 
  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push 038462784735.dkr.ecr.us-east-2.amazonaws.com/energy-frontend-v2
      - docker push 038462784735.dkr.ecr.us-east-2.amazonaws.com/energy-backend-v2
 
      - echo Updating Kubernetes deployment on EKS...
      - aws eks update-kubeconfig --region us-east-2 --name MyRenamedEKSCluster
 
      - echo Copying Kubernetes YAMLs to root for CodePipeline...
      - cp community-energy-connect-Final/k8s/backend-deployment.yaml .
      - cp community-energy-connect-Final/k8s/backend-service.yaml .
      - cp community-energy-connect-Final/k8s/frontend-deployment.yaml .
      - cp community-energy-connect-Final/k8s/frontend-service.yaml .
 
      # Check & copy ingress.yaml only if not already in root
      - if [ "$(dirname community-energy-connect-Final/k8s/ingress.yaml)" != "." ]; then cp community-energy-connect-Final/k8s/ingress.yaml .; else echo "ingress.yaml already in root, skipping copy"; fi
 
      - echo "Final root directory content:"
      - ls -lh
 
artifacts:
  files:
    - backend-deployment1.yaml
    - frontend-deployment1.yaml
    - ingress.yaml
