version: 0.2

env:
  variables:
    ECR_REGISTRY: 038462784735.dkr.ecr.us-east-1.amazonaws.com
    FRONTEND_IMAGE_NAME: energy-frontend
    BACKEND_IMAGE_NAME: energy-backend

phases:
  install:
    commands:
      - echo "Installing prerequisites..."
      - aws --version
      - docker --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Using image tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building frontend image..."
      - "docker build -t $FRONTEND_IMAGE_NAME:$IMAGE_TAG ./community-energy-connect-Final/frontend"
      - "docker tag $FRONTEND_IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$FRONTEND_IMAGE_NAME:$IMAGE_TAG"

      - echo "Building backend image..."
      - "docker build -t $BACKEND_IMAGE_NAME:$IMAGE_TAG ./community-energy-connect-Final/backend"
      - "docker tag $BACKEND_IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$BACKEND_IMAGE_NAME:$IMAGE_TAG"

  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - "docker push $ECR_REGISTRY/$FRONTEND_IMAGE_NAME:$IMAGE_TAG"
      - "docker push $ECR_REGISTRY/$BACKEND_IMAGE_NAME:$IMAGE_TAG"

      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region us-east-1 --name MyRenamedEKSCluster

      - echo "Updating frontend deployment image..."
      - "kubectl set image deployment/energy-frontend-deployment energy-frontend=$ECR_REGISTRY/$FRONTEND_IMAGE_NAME:$IMAGE_TAG"

      - echo "Updating backend deployment image..."
      - "kubectl set image deployment/energy-backend-deployment energy-backend=$ECR_REGISTRY/$BACKEND_IMAGE_NAME:$IMAGE_TAG"

artifacts:
  files:
    - community-energy-connect-Final/k8s/*.yaml
