version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - IMAGE_TAG=v$CODEBUILD_BUILD_NUMBER
      - echo "Image tag: $IMAGE_TAG"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 038462784735.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building frontend Docker image...
      - docker build -t energy-frontend:$IMAGE_TAG ./community-energy-connect-Final/frontend
      - docker tag energy-frontend:$IMAGE_TAG 038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-frontend:$IMAGE_TAG
      - echo Building backend Docker image...
      - docker build -t energy-backend:$IMAGE_TAG ./community-energy-connect-Final/backend
      - docker tag energy-backend:$IMAGE_TAG 038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-backend:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push 038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-frontend:$IMAGE_TAG
      - docker push 038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-backend:$IMAGE_TAG

      - echo Updating Kubernetes deployment on EKS...
      - aws eks update-kubeconfig --region us-east-1 --name MyRenamedEKSCluster

      - echo Patching frontend deployment with new image...
      - kubectl set image deployment/frontend-deployment frontend-container=038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-frontend:$IMAGE_TAG

      - echo Patching backend deployment with new image...
      - kubectl set image deployment/backend-deployment backend-container=038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-backend:$IMAGE_TAG

artifacts:
  files:
    - community-energy-connect-Final/k8s/*.yaml
