version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ECR_ACCOUNT_ID: 156041402660
    BACKEND_IMAGE_NAME: product-backend
    FRONTEND_IMAGE_NAME: product-frontend
    SONAR_HOST_URL: http://44.204.129.61
    SONAR_TOKEN: sqp_c83454a4a6dc236ca147d7e3203a22eb55daa5dc

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Starting install phase..."
      - set -e
      - if command -v yum >/dev/null 2>&1; then yum install -y jq; fi
      - if command -v apt-get >/dev/null 2>&1; then apt-get update && apt-get install -y jq; fi

      - echo "Installing Trivy..."
      - apt-get install -y wget apt-transport-https gnupg lsb-release
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | tee /usr/share/keyrings/trivy.gpg > /dev/null
      - echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee -a /etc/apt/sources.list.d/trivy.list
      - apt-get update && apt-get install -y trivy

      - echo "Logging in to Docker Hub (if needed)..."
      - if [[ -n "$DOCKER_HUB_USERNAME" && -n "$DOCKER_HUB_PASSWORD" ]]; then echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin; fi

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - echo "Installing SonarScanner for .NET..."
      - dotnet tool install --global dotnet-sonarscanner
      - export PATH="$PATH:/root/.dotnet/tools"

  pre_build:
    commands:
      - echo "Setting version tag..."
      - VERSION_TAG=v$CODEBUILD_BUILD_NUMBER
      - export VERSION_TAG
      - echo "Version tag is $VERSION_TAG"

  build:
    commands:
      - echo "Running SonarQube scan..."
      - cd Products_Backend
      - dotnet sonarscanner begin /k:"Dotnet" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.login="$SONAR_TOKEN"
      - dotnet build
      - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
      - echo "Building backend image..."
      - docker build -t $BACKEND_IMAGE_NAME:$VERSION_TAG .
      - docker tag $BACKEND_IMAGE_NAME:$VERSION_TAG $ECR_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACKEND_IMAGE_NAME:$VERSION_TAG
      - cd ..

      - echo "Building frontend image..."
      - cd Products_UI
      - docker build -t $FRONTEND_IMAGE_NAME:$VERSION_TAG .
      - docker tag $FRONTEND_IMAGE_NAME:$VERSION_TAG $ECR_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$FRONTEND_IMAGE_NAME:$VERSION_TAG
      - cd ..

      - echo "Running Trivy scan on backend image..."
      - trivy image --severity HIGH,CRITICAL $BACKEND_IMAGE_NAME:$VERSION_TAG || echo "Vulnerabilities found in backend image"

      - echo "Running Trivy scan on frontend image..."
      - trivy image --severity HIGH,CRITICAL $FRONTEND_IMAGE_NAME:$VERSION_TAG || echo "Vulnerabilities found in frontend image"

  post_build:
    commands:
      - echo "Pushing backend image to ECR..."
      - docker push $ECR_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACKEND_IMAGE_NAME:$VERSION_TAG

      - echo "Pushing frontend image to ECR..."
      - docker push $ECR_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$FRONTEND_IMAGE_NAME:$VERSION_TAG

      - echo "Copying Kubernetes manifests to root directory..."
      - cp cloudformation_deploy/backend-deployment.yaml . || echo "Missing backend-deployment.yaml"
      - cp cloudformation_deploy/frontend-deployment.yaml . || echo "Missing frontend-deployment.yaml"
      - cp cloudformation_deploy/ingress.yaml . || echo "Missing ingress.yaml"

      - echo "Final workspace contents:"
      - ls -lh

artifacts:
  files:
    - backend-deployment.yaml
    - frontend-deployment.yaml
    - ingress.yaml
