apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-backend
  labels:
    app: php-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-backend
  template:
    metadata:
      labels:
        app: php-backend
    spec:
      containers:
        - name: php-backend
          image: 038462784735.dkr.ecr.us-east-1.amazonaws.com/energy-backend:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: rds-credentials
                  key: DB_PASS
