apiVersion: v1
kind: Service
metadata:
  name: php-backend
  labels:
    app: php-backend
spec:
  selector:
    app: php-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
