version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    AWS_REGION: us-east-1
    FRONTEND_REPO: 038462784735.dkr.ecr.us-east-1.amazonaws.com/php-frontend
    BACKEND_REPO: 038462784735.dkr.ecr.us-east-1.amazonaws.com/php-backend

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - echo "Docker login successful"
      - echo "Setting IMAGE_TAG as latest or from CodeBuild env"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      - echo "Building Docker images..."
      - docker build -t $FRONTEND_REPO:$IMAGE_TAG ./frontend
      - docker build -t $BACKEND_REPO:$IMAGE_TAG ./backend
      - echo "Docker images built"

  post_build:
    commands:
      - echo "Pushing Docker images to ECR..."
      - docker push $FRONTEND_REPO:$IMAGE_TAG
      - docker push $BACKEND_REPO:$IMAGE_TAG
      - echo "Updating Kubernetes manifests with new image tags..."
      - sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/frontend/deployment.yaml
      - sed -i "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/backend/deployment.yaml
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f k8s/namespace.yaml
      - kubectl apply -f k8s/secrets/
      - kubectl apply -f k8s/backend/
      - kubectl apply -f k8s/frontend/
      - kubectl apply -f k8s/ingress.yaml
      - echo "Deployment to EKS completed"

artifacts:
  files:
    - k8s/**/*
