apiVersion: v1
kind: Secret
metadata:
  name: rds-credentials
type: Opaque
stringData:
  DB_HOST: eks-tree-rds.ch2c82wwifaa.us-east-1.rds.amazonaws.com
  DB_NAME: community_energy_connect
  DB_USER: admin
  DB_PASS: khaleeda
