apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: energy-backend
  template:
    metadata:
      labels:
        app: energy-backend
    spec:
      containers:
        - name: energy-backend
          image: 038462784735.dkr.ecr.us-east-2.amazonaws.com/energy-backend-v2@sha256:234ea5c1975bcfdea071540a933976f670512257db65977c9b67241687bda911
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mymysqlinstance.ctcqusy24box.us-east-2.rds.amazonaws.com
            - name: DB_NAME
              value: test
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: khaleeda
---
apiVersion: v1
kind: Service
metadata:
  name: energy-backend-service
spec:
  type: ClusterIP
  selector:
    app: energy-backend
  ports:
    - port: 80
      targetPort: 80
